version: '3'

services:
  backend:
    build: ./TP_EVENT_API
    container_name: event-backend
    ports:
      - "9001:9001"
    environment:
      - PORT=9001
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=eventdb
    depends_on:
      - postgres
    command: sh -c "sleep 10 && npm start"

  frontend:
    build: ./TP_EVENT_WEB_APP
    ports:
      - "8081:80"
    depends_on:
      - backend

  postgres:
    image: postgres:17
    container_name: event-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eventdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

   