name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_TOKEN }}



    - name: Build and push backend image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/projet-devops-backend ./backend
        docker push ${{ secrets.DOCKER_USERNAME }}/projet-devops-backend

    - name: Build and push frontend image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/projet-devops-frontend ./frontend
        docker push ${{ secrets.DOCKER_USERNAME }}/projet-devops-frontend

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.REMOTE_SSH_KEY }}
        script: |
          cd ~/projet-devOps
          git pull origin main
          docker compose down
          docker compose pull
          docker compose up -d --build
